name: CI/CD with Gradle, Java17(corretto)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test workflows
      run: |
        echo hi
        ls

    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle Wrapper
      run: |
        ./gradlew build

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Gradle Test
      run: |
        ./gradlew test
